[EventService] Testing
MLGMAG/IASA_Organiser pull request #100
Opened 2020-11-26 17:45 UTC by makrushinoff

2020-11-26 18:06 UTC, MLGMAG requested changes

2020-11-26 18:06 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
> +    }
Fix method and test

2020-11-26 18:06 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
> +        DefaultFileDataManager fileDataManager1 = DefaultFileDataManager.getInstance();
What is unit test?
Why you are writing integration test instead of unit test?

2020-11-26 18:06 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
Fix spacing

2020-11-26 18:06 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
>  import ua.kpi.iasa.IASA_Organiser.service.EventService;
Remove redundant imports

2020-11-26 18:06 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
>  import ua.kpi.iasa.IASA_Organiser.data.GenericDataManager;
Remove redundant import

2020-11-26 18:21 UTC, makrushinoff commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
> +        throw new UnsupportedOperationException("You refer to unsupported method");
Done

2020-11-26 18:21 UTC, VasiliyPetrov1 approved these changes

2020-11-26 18:22 UTC, VasiliyPetrov1 approved these changes

2020-11-26 18:25 UTC, MLGMAG requested changes

2020-11-26 18:25 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
> -//    }
Why do you removed that test?

2020-11-26 18:29 UTC, MLGMAG commented
@makrushinoff 
Add unit test for method getAllEventsList in EventService

2020-11-26 18:50 UTC, MLGMAG requested changes

2020-11-26 18:50 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
> +
Make code format

2020-11-26 18:54 UTC, MLGMAG approved these changes

2020-11-27 00:40 UTC, VasiliyPetrov1 approved these changes

2020-11-27 00:40 UTC, merged