[CalendarService] Add documentation
MLGMAG/IASA_Organiser pull request #145
Opened 2020-12-22 19:02 UTC by VasiliyPetrov1

Add documentation to all CalendarService methods
besides getExpiredEvents()

2020-12-22 20:46 UTC, MLGMAG requested changes

2020-12-22 20:46 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> + */
Add @author and @see

2020-12-22 20:46 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> +import ua.kpi.iasa.IASA_Organiser.controller.Controller;
Redundant import

2020-12-22 20:46 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> +import ua.kpi.iasa.IASA_Organiser.view.View;
Redundant import

2020-12-22 20:46 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> +import java.util.GregorianCalendar;
Redundant import

2020-12-22 21:46 UTC, MLGMAG approved these changes

2020-12-23 11:38 UTC, makrushinoff approved these changes

2020-12-23 11:38 UTC, merged