[EventDestribution] create basic Structure and change Calendar
MLGMAG/IASA_Organiser pull request #53
Opened 2020-11-17 12:58 UTC by VasiliyPetrov1

2020-11-17 13:04 UTC, MLGMAG requested changes

2020-11-17 13:04 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventDestributionService.java
> +    /* this class is Publisher in Observer pattern
Add java docs to class with this comment. 
You can see example in PR#52

2020-11-17 13:04 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/model/Calendar.java
>      private Event[] events;
Recode Array to List

2020-11-17 13:06 UTC, VasiliyPetrov1 commented on src/main/java/ua/kpi/iasa/IASA_Organiser/model/Calendar.java
>      private Event[] events;
Yes nice idea)

2020-11-17 13:06 UTC, makrushinoff requested changes

2020-11-17 13:06 UTC, makrushinoff commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventDestributionService.java
> +
If you want to make singleton, you should create private constructor

2020-11-17 20:49 UTC, MLGMAG requested changes

2020-11-17 20:49 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/data/EventDistributionContainer.java
> +public interface EventDistributionContainer {
YAGNI

2020-11-17 20:54 UTC, MLGMAG approved these changes

2020-11-17 20:54 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> +    private GenericDataManager dataManager = DefaultFileDataManager.getInstance();
Cool)

2020-11-17 21:15 UTC, MLGMAG approved these changes

2020-11-18 08:16 UTC, makrushinoff approved these changes

2020-11-18 08:16 UTC, merged