[CalendarService] Add API
MLGMAG/IASA_Organiser pull request #81
Opened 2020-11-22 00:17 UTC by VasiliyPetrov1

Adding List<Event> getEventsBeforeDate(LocalDate date)
and List<Event> sortEventsByDate(List<Event> sortedList)
methods

2020-11-22 10:47 UTC, MLGMAG requested changes

2020-11-22 10:47 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> +        List<Event> beforeDateList = new ArrayList<>();
Extract to package-private method, that would create new ArrayList

2020-11-22 10:47 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
> +        }
Replace with Lambda-expression

2020-11-23 20:47 UTC, MLGMAG approved these changes

2020-11-23 20:48 UTC, makrushinoff approved these changes

2020-11-23 20:48 UTC, merged