[ControllerTests] Adopted Controller for testing and make more correct Controller tests
MLGMAG/IASA_Organiser pull request #84
Opened 2020-11-22 18:36 UTC by makrushinoff

2020-11-22 18:54 UTC, MLGMAG requested changes
Good job, fix some issues and tag me

2020-11-22 18:54 UTC, MLGMAG commented on src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
> +        return currentCalendarService.sortEventsByPriority();
Add final key-word to local variables (currentCalendarService)

2020-11-22 18:54 UTC, MLGMAG commented on src/test/java/ua/kpi/iasa/IASA_Organiser/controller/ControllerTest.java
>  import ua.kpi.iasa.IASA_Organiser.model.Calendar;
Redundant import

2020-11-23 09:19 UTC, VasiliyPetrov1 submitted a review, later dismissed

2020-11-23 18:47 UTC, MLGMAG approved these changes

2020-11-23 20:06 UTC, VasiliyPetrov1 approved these changes

2020-11-23 20:08 UTC, merged

2020-11-23 20:09 UTC, VasiliyPetrov1 approved these changes